name: chordsbandkompok
description: A Flutter app for managing songs.

publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.5
  file_selector: ^1.0.3
  path_provider: ^2.1.3
  open_file: ^3.3.2
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
